advanced:
  log_level: INFO
  streamable_http_path: /api/mcp
server:
  host: localhost
  instructions: FastMCP-Factory demo server providing calculation functionality and management tools
  name: demo-server
  port: 8888
  transport: streamable-http
tools:
  expose_management_tools: true
