# FastMCP-Factory Basic Server Configuration
# Basic server configuration - Entry-level example

server:
  name: "basic-mcp-server"
  instructions: "This is a basic MCP server example demonstrating FastMCP-Factory core functionality"

# Transport and connection settings
runtime:
  transport: "stdio"  # Use standard input/output, suitable for command line tools
  host: "localhost"
  port: 8080
  log_level: "INFO"

# Middleware configuration (optional)
# middleware:
#   - type: "logging"
#     enabled: true
#     config:
#       include_payloads: false
#       max_payload_length: 1000
#       log_level: 20

# Tool configuration
tools:
  expose_management_tools: true  # Expose management tools for debugging convenience

# Advanced settings
advanced:
  debug: true
  on_duplicate_tools: "warn"
